apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-config
  labels:
    app: seaweedfs
    component: filer
stringData:
  s3.json: |
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": "641b8044601341492ac0",
              "secretKey": "87f2c83e72e19fe13cde8f83b4b5ea76096afff2"
            }
          ],
          "actions": [
            "Admin",
            "Read",
            "Write",
            "List",
            "Tagging"
          ]
        }
      ]
    }
