apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitlab-rails-secret
spec:
  type: kv-v2
  mount: devinfra
  path: infra/gitlab/stage/rails-secret
  destination:
    name: gitlab-rails-secret
    create: true
    type: Opaque
    transformation:
      excludeRaw: true
      templates:
        secrets.yml:
          text: |
            production:
              secret_key_base: {{ .Secrets.secret_key_base }}
              otp_key_base: {{ .Secrets.otp_key_base }}
              db_key_base: {{ .Secrets.db_key_base }}
              encrypted_settings_key_base: {{ .Secrets.encrypted_settings_key_base }}
              openid_connect_signing_key: |
                {{ .Secrets.openid_connect_signing_key | indent 4 }}
              ci_jwt_signing_key: |
                {{ .Secrets.ci_jwt_signing_key | indent 4 }}
  refreshAfter: 30s
  vaultAuthRef: gitlab-stage
