---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: s3-backup-creds
spec:
  type: kv-v2
  mount: devinfra
  path: infra/gitlab/stage/s3
  destination:
    name: s3-backup-creds
    create: true
    type: Opaque
    transformation:
      excludeRaw: true
      templates:
        config:
          text: |
            [default]
            aws_access_key_id = {{ .Secrets.access_key }}
            aws_secret_access_key = {{ .Secrets.secret_key }}
            bucket_location = {{ .Secrets.region }}
            host_base = {{ .Secrets.endpoint }}
            host_bucket = {{ .Secrets.endpoint }}
            use_https = False
            signature_v2 = False
  refreshAfter: 30s
  vaultAuthRef: gitlab-stage
